// Code generated by MockGen. DO NOT EDIT.
// Source: ./grpc.go
//
// Generated by this command:
//
//	mockgen -source=./grpc.go -destination=./mock/grpc.go -package=mockInventoryRepository
//

// Package mockInventoryRepository is a generated GoMock package.
package mockInventoryRepository

import (
	context "context"
	reflect "reflect"

	inventory "github.com/hifat/mallow-sale-api/internal/inventory"
	gomock "go.uber.org/mock/gomock"
)

// MockIInventoryGRPCRepository is a mock of IInventoryGRPCRepository interface.
type MockIInventoryGRPCRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInventoryGRPCRepositoryMockRecorder
}

// MockIInventoryGRPCRepositoryMockRecorder is the mock recorder for MockIInventoryGRPCRepository.
type MockIInventoryGRPCRepositoryMockRecorder struct {
	mock *MockIInventoryGRPCRepository
}

// NewMockIInventoryGRPCRepository creates a new mock instance.
func NewMockIInventoryGRPCRepository(ctrl *gomock.Controller) *MockIInventoryGRPCRepository {
	mock := &MockIInventoryGRPCRepository{ctrl: ctrl}
	mock.recorder = &MockIInventoryGRPCRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInventoryGRPCRepository) EXPECT() *MockIInventoryGRPCRepositoryMockRecorder {
	return m.recorder
}

// FindIn mocks base method.
func (m *MockIInventoryGRPCRepository) FindIn(ctx context.Context, filter inventory.FilterReq) ([]inventory.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIn", ctx, filter)
	ret0, _ := ret[0].([]inventory.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIn indicates an expected call of FindIn.
func (mr *MockIInventoryGRPCRepositoryMockRecorder) FindIn(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIn", reflect.TypeOf((*MockIInventoryGRPCRepository)(nil).FindIn), ctx, filter)
}
