// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mockInventoryRepository
//

// Package mockInventoryRepository is a generated GoMock package.
package mockInventoryRepository

import (
	context "context"
	reflect "reflect"

	inventory "github.com/hifat/mallow-sale-api/internal/inventory"
	gomock "go.uber.org/mock/gomock"
)

// MockIInventoryRepository is a mock of IInventoryRepository interface.
type MockIInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInventoryRepositoryMockRecorder
}

// MockIInventoryRepositoryMockRecorder is the mock recorder for MockIInventoryRepository.
type MockIInventoryRepositoryMockRecorder struct {
	mock *MockIInventoryRepository
}

// NewMockIInventoryRepository creates a new mock instance.
func NewMockIInventoryRepository(ctrl *gomock.Controller) *MockIInventoryRepository {
	mock := &MockIInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockIInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInventoryRepository) EXPECT() *MockIInventoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIInventoryRepository) Create(ctx context.Context, req inventory.InventoryReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIInventoryRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInventoryRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockIInventoryRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIInventoryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIInventoryRepository)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockIInventoryRepository) Find(ctx context.Context) ([]inventory.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]inventory.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIInventoryRepositoryMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIInventoryRepository)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockIInventoryRepository) FindByID(ctx context.Context, id string) (*inventory.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*inventory.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIInventoryRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIInventoryRepository)(nil).FindByID), ctx, id)
}

// FindIn mocks base method.
func (m *MockIInventoryRepository) FindIn(ctx context.Context, filter inventory.FilterReq) ([]inventory.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIn", ctx, filter)
	ret0, _ := ret[0].([]inventory.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIn indicates an expected call of FindIn.
func (mr *MockIInventoryRepositoryMockRecorder) FindIn(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIn", reflect.TypeOf((*MockIInventoryRepository)(nil).FindIn), ctx, filter)
}

// Update mocks base method.
func (m *MockIInventoryRepository) Update(ctx context.Context, id string, req inventory.InventoryReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIInventoryRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIInventoryRepository)(nil).Update), ctx, id, req)
}
