// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package recipeDI

import (
	"github.com/google/wire"
	"github.com/hifat/cost-calculator-api/internal/recipe/recipeHandler"
	"github.com/hifat/cost-calculator-api/internal/recipe/recipeRepository"
	"github.com/hifat/cost-calculator-api/internal/recipe/recipeService"
	"github.com/hifat/goroger-core/helper"
	"github.com/hifat/goroger-core/logger"
	"go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func Init(db *mongo.Database, log *zap.Logger) recipeHandler.Handler {
	coreHelper := helper.New()
	iRecipeRepository := recipeRepository.NewMongo(db, coreHelper)
	coreLogger := logger.New(log)
	iRecipeService := recipeService.New(iRecipeRepository, coreLogger)
	recipeRest := recipeHandler.NewRest(iRecipeService)
	handler := recipeHandler.New(recipeRest)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(recipeRepository.NewMongo)

var ServiceSet = wire.NewSet(logger.New, recipeService.New)

var HandlerSet = wire.NewSet(helper.New, recipeHandler.New, recipeHandler.NewRest)
