// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package recipeDI

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/hifat/mallow-sale-api/internal/inventory/inventoryRepository"
	"github.com/hifat/mallow-sale-api/internal/recipe/recipeHandler"
	"github.com/hifat/mallow-sale-api/internal/recipe/recipeRepository"
	"github.com/hifat/mallow-sale-api/internal/recipe/recipeService"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/usageUnitRepository"
	"github.com/hifat/mallow-sale-api/pkg/utils/serviceUtils"
	"github.com/hifat/goroger-core/helper"
	"github.com/hifat/goroger-core/logger"
	"github.com/hifat/goroger-core/rules"
	"go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func Init(db *mongo.Database, log *zap.Logger, validate *validator.Validate) recipeHandler.Handler {
	coreLogger := logger.New(log)
	rulesValidator := rules.New(validate)
	coreHelper := helper.New()
	iUsageUnitRepository := usageUnitRepository.NewMongo(db)
	iUsageUnitServiceUtils := usageUnitServiceUtils.New(iUsageUnitRepository)
	iRecipeRepository := recipeRepository.NewMongo(db, coreHelper)
	iInventoryRepository := inventoryRepository.NewMongo(db, coreHelper)
	iRecipeService := recipeService.New(coreLogger, rulesValidator, coreHelper, iUsageUnitServiceUtils, iRecipeRepository, iInventoryRepository)
	recipeRest := recipeHandler.NewRest(iRecipeService)
	handler := recipeHandler.New(recipeRest)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(recipeRepository.NewMongo, usageUnitRepository.NewMongo, inventoryRepository.NewMongo)

var ServiceSet = wire.NewSet(logger.New, rules.New, helper.New, recipeService.New, usageUnitServiceUtils.New)

var HandlerSet = wire.NewSet(recipeHandler.New, recipeHandler.NewRest)
