// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./mock/service.go -package=mockRecipeRepository
//

// Package mockRecipeRepository is a generated GoMock package.
package mockRecipeRepository

import (
	context "context"
	reflect "reflect"

	recipe "github.com/hifat/mallow-sale-api/internal/recipe"
	gomock "go.uber.org/mock/gomock"
)

// MockIRecipeService is a mock of IRecipeService interface.
type MockIRecipeService struct {
	ctrl     *gomock.Controller
	recorder *MockIRecipeServiceMockRecorder
}

// MockIRecipeServiceMockRecorder is the mock recorder for MockIRecipeService.
type MockIRecipeServiceMockRecorder struct {
	mock *MockIRecipeService
}

// NewMockIRecipeService creates a new mock instance.
func NewMockIRecipeService(ctrl *gomock.Controller) *MockIRecipeService {
	mock := &MockIRecipeService{ctrl: ctrl}
	mock.recorder = &MockIRecipeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecipeService) EXPECT() *MockIRecipeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRecipeService) Create(ctx context.Context, req recipe.RecipeReq) (*recipe.RecipeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*recipe.RecipeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIRecipeServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRecipeService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockIRecipeService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRecipeServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRecipeService)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockIRecipeService) Find(ctx context.Context) ([]recipe.RecipeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]recipe.RecipeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIRecipeServiceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIRecipeService)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockIRecipeService) FindByID(ctx context.Context, id string) (*recipe.RecipeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*recipe.RecipeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIRecipeServiceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIRecipeService)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockIRecipeService) Update(ctx context.Context, id string, req recipe.UpdateRecipeReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRecipeServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRecipeService)(nil).Update), ctx, id, req)
}
