// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package recipeDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/recipe/handler"
	"github.com/hifat/mallow-sale-api/internal/recipe/repository"
	"github.com/hifat/mallow-sale-api/internal/recipe/service"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/helper"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *recipeHandler.Handler {
	loggerLogger := logger.New()
	repository := recipeRepository.NewMongo(db)
	inventoryRepositoryRepository := inventoryRepository.NewMongo(db)
	usageUnitRepositoryRepository := usageUnitRepository.NewMongo(db)
	usageUnitHelperHelper := usageUnitHelper.New(loggerLogger, usageUnitRepositoryRepository)
	helperHelper := helper.New(inventoryRepositoryRepository)
	serviceService := service.New(loggerLogger, repository, inventoryRepositoryRepository, usageUnitRepositoryRepository, usageUnitHelperHelper, helperHelper)
	rest := recipeHandler.NewRest(serviceService)
	handler := recipeHandler.New(rest)
	return handler
}
