// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package recipeDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/recipe/handler"
	"github.com/hifat/mallow-sale-api/internal/recipe/helper"
	"github.com/hifat/mallow-sale-api/internal/recipe/repository"
	"github.com/hifat/mallow-sale-api/internal/recipe/service"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/helper"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *recipeHandler.Handler {
	iLogger := logger.New()
	iRepository := recipeRepository.NewMongo(db)
	inventoryRepositoryIRepository := inventoryRepository.NewMongo(db)
	usageUnitRepositoryIRepository := usageUnitRepository.NewMongo(db)
	iHelper := usageUnitHelper.New(iLogger, usageUnitRepositoryIRepository)
	helperIHelper := helper.New(inventoryRepositoryIRepository)
	typeRepository := recipeRepository.NewTypeMongo(db)
	recipeTypeHelper := recipeHelper.NewRecipeTypeHelper(typeRepository)
	iService := service.New(iLogger, iRepository, inventoryRepositoryIRepository, usageUnitRepositoryIRepository, iHelper, helperIHelper, recipeTypeHelper)
	rest := recipeHandler.NewRest(iService)
	handler := recipeHandler.New(rest)
	return handler
}
