// Code generated by MockGen. DO NOT EDIT.
// Source: ./inventoryService_test.go
//
// Generated by this command:
//
//	mockgen -source=./inventoryService_test.go -destination=./mock/mock.go -package=mockInventoryRepository
//

// Package mockInventoryRepository is a generated GoMock package.
package mockInventoryRepository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFoo is a mock of Foo interface.
type MockFoo struct {
	ctrl     *gomock.Controller
	recorder *MockFooMockRecorder
}

// MockFooMockRecorder is the mock recorder for MockFoo.
type MockFooMockRecorder struct {
	mock *MockFoo
}

// NewMockFoo creates a new mock instance.
func NewMockFoo(ctrl *gomock.Controller) *MockFoo {
	mock := &MockFoo{ctrl: ctrl}
	mock.recorder = &MockFooMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFoo) EXPECT() *MockFooMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockFoo) Copy(toValue, fromValue any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", toValue, fromValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockFooMockRecorder) Copy(toValue, fromValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockFoo)(nil).Copy), toValue, fromValue)
}
