services:
   jenkins-docker:
      image: docker:dind
      container_name: jenkins-docker
      privileged: true
      environment:
         - DOCKER_TLS_CERTDIR=/certs
      volumes:
         - ./data/certs:/certs/client
         - ./data/jenkins_home:/var/jenkins_home
      ports:
         - '2376:2376'
      networks:
         jenkins:
            aliases:
               - docker
      command: --storage-driver overlay2

   my-jenkins:
      image: my-jenkins
      build:
         dockerfile: Dockerfile.jenkins
         context: .
      container_name: my-jenkins
      restart: on-failure
      environment:
         - DOCKER_HOST=tcp://docker:2376
         - DOCKER_CERT_PATH=/certs/client
         - DOCKER_TLS_VERIFY=1
      volumes:
         - ./data/jenkins_home:/var/jenkins_home
         - ./data/certs:/certs/client:ro
      ports:
         - '8081:8080'
         - '50000:50000'
      networks:
         - jenkins
   
   sonarqube:
      image: sonarqube:community
      container_name: sonarqube
      ports:
         - 9000:9000
      volumes:
         - ./data/sonarqube/data:/opt/sonarqube/data
         - ./data/sonarqube/logs:/opt/sonarqube/logs
         - ./data/sonarqube/extensions:/opt/sonarqube/extensions

networks:
   jenkins:
      driver: bridge

volumes:
   jenkins-docker-certs:
   jenkins-data:
