services:
   mongo:
      image: mongo
      restart: always
      container_name: mongo
      ports:
         - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: 123456
      volumes:
         - ./data/mongo:/data/db
  
   jenkins:
      build: 
         context: .
         dockerfile: Dockerfile.jenkins
      restart: always
      container_name: jenkins
      ports:
         - 8081:8080
         - 50000:50000
      volumes:
         - ./data/jenkins_home:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock
