services:
   mongo:
      image: mongo
      restart: always
      container_name: mongo
      ports:
         - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: 123456
      volumes:
         - ./data/mongo:/data/db

   mls-api:
      build: 
         context: .
         dockerfile: Dockerfile
      container_name: mallow-sale-api
      ports:
         - 4001:4000
      volumes:
         - ./env:/app/env
      command: ["--envPath", "/app/env/.env.local"]
      restart: always
