// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package storageDi

import (
	storageHandler "github.com/hifat/mallow-sale-api/internal/storage/handler"
	storageRepository "github.com/hifat/mallow-sale-api/internal/storage/repository"
	storageService "github.com/hifat/mallow-sale-api/internal/storage/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
)

// Injectors from wire.go:

func Init(cfg *config.Config) (*storageHandler.Handler, error) {
	iRepository, err := storageRepository.NewGDrive(cfg)
	if err != nil {
		return nil, err
	}
	iLogger := logger.New()
	iService := storageService.New(iLogger, iRepository)
	rest := storageHandler.NewRest(iService)
	handler := storageHandler.New(rest)
	return handler, nil
}
