// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package storageDi

import (
	"github.com/hifat/mallow-sale-api/internal/storage/handler"
	"github.com/hifat/mallow-sale-api/internal/storage/helper"
	"github.com/hifat/mallow-sale-api/internal/storage/repository"
	"github.com/hifat/mallow-sale-api/internal/storage/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

//
//go:generate wire ./wire.go
func Init(cfg *config.Config, grpcConn *grpc.ClientConn) *storageHandler.Handler {
	iGrpcRepository := storagerepo.NewGrpcRepository(cfg, grpcConn)
	iHelper := storageHelper.New(cfg)
	iService := storagesvc.New(cfg, iGrpcRepository, iHelper)
	rest := storageHandler.NewRest(iService)
	handler := storageHandler.New(rest)
	return handler
}
