// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package promotionDi

import (
	"github.com/hifat/mallow-sale-api/internal/promotion/handler"
	"github.com/hifat/mallow-sale-api/internal/promotion/repository"
	"github.com/hifat/mallow-sale-api/internal/promotion/service"
	"github.com/hifat/mallow-sale-api/internal/recipe/helper"
	"github.com/hifat/mallow-sale-api/internal/recipe/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *promotionHandler.Handler {
	iLogger := logger.New()
	iRepository := promotionRepository.NewMongo(db)
	recipeRepositoryIRepository := recipeRepository.NewMongo(db)
	iHelper := recipeHelper.New(recipeRepositoryIRepository)
	iService := recipeService.New(iLogger, iRepository, iHelper)
	rest := promotionHandler.NewRest(iService)
	handler := promotionHandler.New(rest)
	return handler
}
