// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package promotionDi

import (
	"github.com/hifat/mallow-sale-api/internal/promotion/handler"
	"github.com/hifat/mallow-sale-api/internal/promotion/repository"
	"github.com/hifat/mallow-sale-api/internal/promotion/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *promotionHandler.Handler {
	loggerLogger := logger.New()
	repository := promotionRepository.NewMongo(db)
	serviceService := service.New(loggerLogger, repository)
	rest := promotionHandler.NewRest(serviceService)
	handler := promotionHandler.New(rest)
	return handler
}
