// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usageUnitDi

import (
	"github.com/google/wire"
	"github.com/hifat/goroger-core/helper"
	"github.com/hifat/goroger-core/logger"
	"github.com/hifat/mallow-sale-api/config"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/usageUnitHandler"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/usageUnitRepository"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/usageUnitService"
	"github.com/hifat/mallow-sale-api/pkg/rpc"
	"go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database, log *zap.Logger, grpc rpc.GrpcClient) usageUnitHandler.Handler {
	coreLogger := logger.New(log)
	iUsageUnitRepository := usageUnitRepository.NewMongo(db)
	iUsageUnitService := usageUnitService.New(coreLogger, iUsageUnitRepository)
	usageUnitGRPC := usageUnitHandler.NewGRPC(iUsageUnitService)
	handler := usageUnitHandler.New(usageUnitGRPC)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(usageUnitRepository.NewMongo)

var ServiceSet = wire.NewSet(helper.New, logger.New, usageUnitService.New)

var HandlerSet = wire.NewSet(usageUnitHandler.New, usageUnitHandler.NewGRPC)
