// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package purchaseDi

import (
	"github.com/hifat/mallow-sale-api/internal/purchase/preset/handler"
	"github.com/hifat/mallow-sale-api/internal/purchase/preset/repository"
	"github.com/hifat/mallow-sale-api/internal/purchase/preset/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *purchasePresetHandler.Handler {
	iLogger := logger.New()
	iRepository := purchasePresetRepository.NewMongo(db)
	iService := purchaseService.New(iLogger, iRepository)
	rest := purchasePresetHandler.NewRest(iService)
	handler := purchasePresetHandler.New(rest)
	return handler
}
