// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package purchaseDi

import (
	"github.com/hifat/mallow-sale-api/internal/purchase/handler"
	"github.com/hifat/mallow-sale-api/internal/purchase/repository"
	"github.com/hifat/mallow-sale-api/internal/purchase/service"
	"github.com/hifat/mallow-sale-api/internal/purchase/supplier/evidence/repository"
	"github.com/hifat/mallow-sale-api/internal/purchase/supplier/order/repository"
	"github.com/hifat/mallow-sale-api/internal/purchase/supplier/repository"
	"github.com/hifat/mallow-sale-api/internal/utils/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *purchaseHandler.Handler {
	iRepository := purchaseRepository.NewMongo(db)
	purchaseSupplierModuleIRepository := purchaseSupplierRepository.NewMongo(db)
	purchaseSupplierOrderModuleIRepository := purchaseSupplierOrderRepository.NewMongo(db)
	purchaseSupplierEvidenceModuleIRepository := purchaseSupplierEvidenceRepository.NewMongo(db)
	utilsModuleIRepository := utilsRepository.NewMongo()
	iService := purchaseService.New(iRepository, purchaseSupplierModuleIRepository, purchaseSupplierOrderModuleIRepository, purchaseSupplierEvidenceModuleIRepository, utilsModuleIRepository)
	rest := purchaseHandler.NewRest(iService)
	handler := purchaseHandler.New(rest)
	return handler
}
