// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/inventory/inventoryProto/inventory.proto

package inventoryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenFilter) Reset() {
	*x = AccessTokenFilter{}
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenFilter) ProtoMessage() {}

func (x *AccessTokenFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenFilter.ProtoReflect.Descriptor instead.
func (*AccessTokenFilter) Descriptor() ([]byte, []int) {
	return file_internal_inventory_inventoryProto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UsageUnitEmbed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageUnitEmbed) Reset() {
	*x = UsageUnitEmbed{}
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageUnitEmbed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageUnitEmbed) ProtoMessage() {}

func (x *UsageUnitEmbed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageUnitEmbed.ProtoReflect.Descriptor instead.
func (*UsageUnitEmbed) Descriptor() ([]byte, []int) {
	return file_internal_inventory_inventoryProto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *UsageUnitEmbed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UsageUnitEmbed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InventoryRes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             float32                `protobuf:"fixed32,2,opt,name=name,proto3" json:"name,omitempty"`
	PurchasePrice    float32                `protobuf:"fixed32,3,opt,name=purchasePrice,proto3" json:"purchasePrice,omitempty"`
	PurchaseQuantity float32                `protobuf:"fixed32,4,opt,name=purchaseQuantity,proto3" json:"purchaseQuantity,omitempty"`
	YieldPercentage  float32                `protobuf:"fixed32,6,opt,name=yieldPercentage,proto3" json:"yieldPercentage,omitempty"`
	Remark           float32                `protobuf:"fixed32,7,opt,name=remark,proto3" json:"remark,omitempty"`
	PurchaseUnit     *UsageUnitEmbed        `protobuf:"bytes,8,opt,name=purchaseUnit,proto3" json:"purchaseUnit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InventoryRes) Reset() {
	*x = InventoryRes{}
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRes) ProtoMessage() {}

func (x *InventoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_inventoryProto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRes.ProtoReflect.Descriptor instead.
func (*InventoryRes) Descriptor() ([]byte, []int) {
	return file_internal_inventory_inventoryProto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryRes) GetName() float32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *InventoryRes) GetPurchasePrice() float32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *InventoryRes) GetPurchaseQuantity() float32 {
	if x != nil {
		return x.PurchaseQuantity
	}
	return 0
}

func (x *InventoryRes) GetYieldPercentage() float32 {
	if x != nil {
		return x.YieldPercentage
	}
	return 0
}

func (x *InventoryRes) GetRemark() float32 {
	if x != nil {
		return x.Remark
	}
	return 0
}

func (x *InventoryRes) GetPurchaseUnit() *UsageUnitEmbed {
	if x != nil {
		return x.PurchaseUnit
	}
	return nil
}

var File_internal_inventory_inventoryProto_inventory_proto protoreflect.FileDescriptor

const file_internal_inventory_inventoryProto_inventory_proto_rawDesc = "" +
	"\n" +
	"1internal/inventory/inventoryProto/inventory.proto\x12\x0einventoryProto\"#\n" +
	"\x11AccessTokenFilter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0eUsageUnitEmbed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xfa\x01\n" +
	"\fInventoryRes\x12\x12\n" +
	"\x04name\x18\x02 \x01(\x02R\x04name\x12$\n" +
	"\rpurchasePrice\x18\x03 \x01(\x02R\rpurchasePrice\x12*\n" +
	"\x10purchaseQuantity\x18\x04 \x01(\x02R\x10purchaseQuantity\x12(\n" +
	"\x0fyieldPercentage\x18\x06 \x01(\x02R\x0fyieldPercentage\x12\x16\n" +
	"\x06remark\x18\a \x01(\x02R\x06remark\x12B\n" +
	"\fpurchaseUnit\x18\b \x01(\v2\x1e.inventoryProto.UsageUnitEmbedR\fpurchaseUnit2h\n" +
	"\x14InventoryGrpcService\x12P\n" +
	"\rFindInventory\x12!.inventoryProto.AccessTokenFilter\x1a\x1c.inventoryProto.InventoryResB\x12Z\x10./inventoryProtob\x06proto3"

var (
	file_internal_inventory_inventoryProto_inventory_proto_rawDescOnce sync.Once
	file_internal_inventory_inventoryProto_inventory_proto_rawDescData []byte
)

func file_internal_inventory_inventoryProto_inventory_proto_rawDescGZIP() []byte {
	file_internal_inventory_inventoryProto_inventory_proto_rawDescOnce.Do(func() {
		file_internal_inventory_inventoryProto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_inventory_inventoryProto_inventory_proto_rawDesc), len(file_internal_inventory_inventoryProto_inventory_proto_rawDesc)))
	})
	return file_internal_inventory_inventoryProto_inventory_proto_rawDescData
}

var file_internal_inventory_inventoryProto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_inventory_inventoryProto_inventory_proto_goTypes = []any{
	(*AccessTokenFilter)(nil), // 0: inventoryProto.AccessTokenFilter
	(*UsageUnitEmbed)(nil),    // 1: inventoryProto.UsageUnitEmbed
	(*InventoryRes)(nil),      // 2: inventoryProto.InventoryRes
}
var file_internal_inventory_inventoryProto_inventory_proto_depIdxs = []int32{
	1, // 0: inventoryProto.InventoryRes.purchaseUnit:type_name -> inventoryProto.UsageUnitEmbed
	0, // 1: inventoryProto.InventoryGrpcService.FindInventory:input_type -> inventoryProto.AccessTokenFilter
	2, // 2: inventoryProto.InventoryGrpcService.FindInventory:output_type -> inventoryProto.InventoryRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_inventory_inventoryProto_inventory_proto_init() }
func file_internal_inventory_inventoryProto_inventory_proto_init() {
	if File_internal_inventory_inventoryProto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_inventory_inventoryProto_inventory_proto_rawDesc), len(file_internal_inventory_inventoryProto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_inventory_inventoryProto_inventory_proto_goTypes,
		DependencyIndexes: file_internal_inventory_inventoryProto_inventory_proto_depIdxs,
		MessageInfos:      file_internal_inventory_inventoryProto_inventory_proto_msgTypes,
	}.Build()
	File_internal_inventory_inventoryProto_inventory_proto = out.File
	file_internal_inventory_inventoryProto_inventory_proto_goTypes = nil
	file_internal_inventory_inventoryProto_inventory_proto_depIdxs = nil
}
