// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package settingDi

import (
	"github.com/hifat/mallow-sale-api/internal/settings/handler"
	"github.com/hifat/mallow-sale-api/internal/settings/repository"
	"github.com/hifat/mallow-sale-api/internal/settings/service"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeSettingsRest(db *mongo.Database) *settingsHandler.Rest {
	iRepository := settingRepository.NewMongo(db)
	iLogger := logger.New()
	iService := settingService.New(iRepository, iLogger)
	rest := settingsHandler.NewRest(iService)
	return rest
}
