// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mockRecipeRepository
//

// Package mockRecipeRepository is a generated GoMock package.
package mockRecipeRepository

import (
	context "context"
	reflect "reflect"

	recipeModule "github.com/hifat/mallow-sale-api/internal/recipe"
	utilsModule "github.com/hifat/mallow-sale-api/internal/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockIRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockIRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockIRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockIRepository) Create(ctx context.Context, recipe *recipeModule.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRepositoryMockRecorder) Create(ctx, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRepository)(nil).Create), ctx, recipe)
}

// DeleteByID mocks base method.
func (m *MockIRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIRepository)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockIRepository) Find(ctx context.Context, query *recipeModule.QueryReq) ([]recipeModule.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, query)
	ret0, _ := ret[0].([]recipeModule.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIRepositoryMockRecorder) Find(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIRepository)(nil).Find), ctx, query)
}

// FindByID mocks base method.
func (m *MockIRepository) FindByID(ctx context.Context, id string) (*recipeModule.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*recipeModule.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIRepository)(nil).FindByID), ctx, id)
}

// FindInIDs mocks base method.
func (m *MockIRepository) FindInIDs(ctx context.Context, ids []string) ([]recipeModule.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInIDs", ctx, ids)
	ret0, _ := ret[0].([]recipeModule.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInIDs indicates an expected call of FindInIDs.
func (mr *MockIRepositoryMockRecorder) FindInIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInIDs", reflect.TypeOf((*MockIRepository)(nil).FindInIDs), ctx, ids)
}

// UpdateByID mocks base method.
func (m *MockIRepository) UpdateByID(ctx context.Context, id string, recipe *recipeModule.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, recipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIRepositoryMockRecorder) UpdateByID(ctx, id, recipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIRepository)(nil).UpdateByID), ctx, id, recipe)
}

// UpdateNoBatch mocks base method.
func (m *MockIRepository) UpdateNoBatch(ctx context.Context, reqs []recipeModule.UpdateOrderNoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNoBatch", ctx, reqs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNoBatch indicates an expected call of UpdateNoBatch.
func (mr *MockIRepositoryMockRecorder) UpdateNoBatch(ctx, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNoBatch", reflect.TypeOf((*MockIRepository)(nil).UpdateNoBatch), ctx, reqs)
}

// MockTypeRepository is a mock of TypeRepository interface.
type MockTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTypeRepositoryMockRecorder
}

// MockTypeRepositoryMockRecorder is the mock recorder for MockTypeRepository.
type MockTypeRepositoryMockRecorder struct {
	mock *MockTypeRepository
}

// NewMockTypeRepository creates a new mock instance.
func NewMockTypeRepository(ctrl *gomock.Controller) *MockTypeRepository {
	mock := &MockTypeRepository{ctrl: ctrl}
	mock.recorder = &MockTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTypeRepository) EXPECT() *MockTypeRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockTypeRepository) Find(ctx context.Context, query *utilsModule.QueryReq) ([]recipeModule.RecipeTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, query)
	ret0, _ := ret[0].([]recipeModule.RecipeTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTypeRepositoryMockRecorder) Find(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTypeRepository)(nil).Find), ctx, query)
}

// FindByCode mocks base method.
func (m *MockTypeRepository) FindByCode(ctx context.Context, code string) (*recipeModule.RecipeTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*recipeModule.RecipeTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockTypeRepositoryMockRecorder) FindByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockTypeRepository)(nil).FindByCode), ctx, code)
}

// FindInCodes mocks base method.
func (m *MockTypeRepository) FindInCodes(ctx context.Context, codes []string) ([]recipeModule.RecipeTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInCodes", ctx, codes)
	ret0, _ := ret[0].([]recipeModule.RecipeTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInCodes indicates an expected call of FindInCodes.
func (mr *MockTypeRepositoryMockRecorder) FindInCodes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInCodes", reflect.TypeOf((*MockTypeRepository)(nil).FindInCodes), ctx, codes)
}
