// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package stockDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/stock/handler"
	"github.com/hifat/mallow-sale-api/internal/stock/repository"
	"github.com/hifat/mallow-sale-api/internal/stock/service"
	"github.com/hifat/mallow-sale-api/internal/supplier/helper"
	"github.com/hifat/mallow-sale-api/internal/supplier/repository"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/helper"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *stockHandler.Handler {
	iRepository := stockRepository.NewMongo(db)
	inventoryRepositoryIRepository := inventoryRepository.NewMongo(db)
	supplierRepositoryIRepository := supplierRepository.NewMongo(db)
	usageUnitRepositoryIRepository := usageUnitRepository.NewMongo(db)
	iHelper := helper.New(inventoryRepositoryIRepository)
	supplierHelperIHelper := supplierHelper.New(supplierRepositoryIRepository)
	iLogger := logger.New()
	usageUnitHelperIHelper := usageUnitHelper.New(iLogger, usageUnitRepositoryIRepository)
	iService := stockService.New(iRepository, inventoryRepositoryIRepository, supplierRepositoryIRepository, usageUnitRepositoryIRepository, iHelper, supplierHelperIHelper, usageUnitHelperIHelper, iLogger)
	rest := stockHandler.NewRest(iService)
	handler := stockHandler.New(rest)
	return handler
}
