// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package stockDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/stock/handler"
	"github.com/hifat/mallow-sale-api/internal/stock/repository"
	"github.com/hifat/mallow-sale-api/internal/stock/service"
	"github.com/hifat/mallow-sale-api/internal/supplier/helper"
	"github.com/hifat/mallow-sale-api/internal/supplier/repository"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/helper"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *stockHandler.Handler {
	repository := stockRepository.NewMongo(db)
	inventoryRepositoryRepository := inventoryRepository.NewMongo(db)
	supplierRepositoryRepository := supplierRepository.NewMongo(db)
	usageUnitRepositoryRepository := usageUnitRepository.NewMongo(db)
	helperHelper := helper.New(inventoryRepositoryRepository)
	supplierHelperHelper := supplierHelper.New(supplierRepositoryRepository)
	loggerLogger := logger.New()
	usageUnitHelperHelper := usageUnitHelper.New(loggerLogger, usageUnitRepositoryRepository)
	service := stockService.New(repository, inventoryRepositoryRepository, supplierRepositoryRepository, usageUnitRepositoryRepository, helperHelper, supplierHelperHelper, usageUnitHelperHelper, loggerLogger)
	rest := stockHandler.NewRest(service)
	handler := stockHandler.New(rest)
	return handler
}
