// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/inventory/proto/inventory.proto

package inventoryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_internal_inventory_proto_inventory_proto_rawDescGZIP(), []int{0}
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_internal_inventory_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Inventory) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Inventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Inventory           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_inventory_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryResponse) GetItems() []*Inventory {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_inventory_proto_inventory_proto protoreflect.FileDescriptor

const file_internal_inventory_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"(internal/inventory/proto/inventory.proto\x12\x0einventoryProto\"\a\n" +
	"\x05Query\"/\n" +
	"\tInventory\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"D\n" +
	"\x11InventoryResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.inventoryProto.InventoryR\x05items2X\n" +
	"\x14InventoryGrpcService\x12@\n" +
	"\x04Find\x12\x15.inventoryProto.Query\x1a!.inventoryProto.InventoryResponseB\x12Z\x10./inventoryProtob\x06proto3"

var (
	file_internal_inventory_proto_inventory_proto_rawDescOnce sync.Once
	file_internal_inventory_proto_inventory_proto_rawDescData []byte
)

func file_internal_inventory_proto_inventory_proto_rawDescGZIP() []byte {
	file_internal_inventory_proto_inventory_proto_rawDescOnce.Do(func() {
		file_internal_inventory_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_inventory_proto_inventory_proto_rawDesc), len(file_internal_inventory_proto_inventory_proto_rawDesc)))
	})
	return file_internal_inventory_proto_inventory_proto_rawDescData
}

var file_internal_inventory_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_inventory_proto_inventory_proto_goTypes = []any{
	(*Query)(nil),             // 0: inventoryProto.Query
	(*Inventory)(nil),         // 1: inventoryProto.Inventory
	(*InventoryResponse)(nil), // 2: inventoryProto.InventoryResponse
}
var file_internal_inventory_proto_inventory_proto_depIdxs = []int32{
	1, // 0: inventoryProto.InventoryResponse.items:type_name -> inventoryProto.Inventory
	0, // 1: inventoryProto.InventoryGrpcService.Find:input_type -> inventoryProto.Query
	2, // 2: inventoryProto.InventoryGrpcService.Find:output_type -> inventoryProto.InventoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_inventory_proto_inventory_proto_init() }
func file_internal_inventory_proto_inventory_proto_init() {
	if File_internal_inventory_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_inventory_proto_inventory_proto_rawDesc), len(file_internal_inventory_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_inventory_proto_inventory_proto_goTypes,
		DependencyIndexes: file_internal_inventory_proto_inventory_proto_depIdxs,
		MessageInfos:      file_internal_inventory_proto_inventory_proto_msgTypes,
	}.Build()
	File_internal_inventory_proto_inventory_proto = out.File
	file_internal_inventory_proto_inventory_proto_goTypes = nil
	file_internal_inventory_proto_inventory_proto_depIdxs = nil
}
