// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: internal/inventory/proto/inventory.proto

package inventoryProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryGrpcServiceClient is the client API for InventoryGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryGrpcServiceClient interface {
	Find(ctx context.Context, in *Query, opts ...grpc.CallOption) (*InventoryResponse, error)
}

type inventoryGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryGrpcServiceClient(cc grpc.ClientConnInterface) InventoryGrpcServiceClient {
	return &inventoryGrpcServiceClient{cc}
}

func (c *inventoryGrpcServiceClient) Find(ctx context.Context, in *Query, opts ...grpc.CallOption) (*InventoryResponse, error) {
	out := new(InventoryResponse)
	err := c.cc.Invoke(ctx, "/inventoryProto.InventoryGrpcService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryGrpcServiceServer is the server API for InventoryGrpcService service.
// All implementations must embed UnimplementedInventoryGrpcServiceServer
// for forward compatibility
type InventoryGrpcServiceServer interface {
	Find(context.Context, *Query) (*InventoryResponse, error)
	mustEmbedUnimplementedInventoryGrpcServiceServer()
}

// UnimplementedInventoryGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryGrpcServiceServer struct {
}

func (UnimplementedInventoryGrpcServiceServer) Find(context.Context, *Query) (*InventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedInventoryGrpcServiceServer) mustEmbedUnimplementedInventoryGrpcServiceServer() {}

// UnsafeInventoryGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryGrpcServiceServer will
// result in compilation errors.
type UnsafeInventoryGrpcServiceServer interface {
	mustEmbedUnimplementedInventoryGrpcServiceServer()
}

func RegisterInventoryGrpcServiceServer(s grpc.ServiceRegistrar, srv InventoryGrpcServiceServer) {
	s.RegisterService(&InventoryGrpcService_ServiceDesc, srv)
}

func _InventoryGrpcService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryGrpcServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventoryProto.InventoryGrpcService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryGrpcServiceServer).Find(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryGrpcService_ServiceDesc is the grpc.ServiceDesc for InventoryGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventoryProto.InventoryGrpcService",
	HandlerType: (*InventoryGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _InventoryGrpcService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/inventory/proto/inventory.proto",
}
