// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mockUsageUnitRepository
//

// Package mockUsageUnitRepository is a generated GoMock package.
package mockUsageUnitRepository

import (
	context "context"
	reflect "reflect"

	usageUnitModule "github.com/hifat/mallow-sale-api/internal/usageUnit"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// FindByCode mocks base method.
func (m *MockIRepository) FindByCode(ctx context.Context, code string) (*usageUnitModule.Prototype, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*usageUnitModule.Prototype)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockIRepositoryMockRecorder) FindByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockIRepository)(nil).FindByCode), ctx, code)
}

// FindInCodes mocks base method.
func (m *MockIRepository) FindInCodes(ctx context.Context, codes []string) ([]usageUnitModule.Prototype, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInCodes", ctx, codes)
	ret0, _ := ret[0].([]usageUnitModule.Prototype)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInCodes indicates an expected call of FindInCodes.
func (mr *MockIRepositoryMockRecorder) FindInCodes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInCodes", reflect.TypeOf((*MockIRepository)(nil).FindInCodes), ctx, codes)
}
