// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./mock/service.go -package=mockUsageUnitService
//

// Package mockUsageUnitService is a generated GoMock package.
package mockUsageUnitService

import (
	context "context"
	reflect "reflect"

	usageUnit "github.com/hifat/mallow-sale-api/internal/usageUnit"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsageUnitService is a mock of IUsageUnitService interface.
type MockIUsageUnitService struct {
	ctrl     *gomock.Controller
	recorder *MockIUsageUnitServiceMockRecorder
}

// MockIUsageUnitServiceMockRecorder is the mock recorder for MockIUsageUnitService.
type MockIUsageUnitServiceMockRecorder struct {
	mock *MockIUsageUnitService
}

// NewMockIUsageUnitService creates a new mock instance.
func NewMockIUsageUnitService(ctrl *gomock.Controller) *MockIUsageUnitService {
	mock := &MockIUsageUnitService{ctrl: ctrl}
	mock.recorder = &MockIUsageUnitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsageUnitService) EXPECT() *MockIUsageUnitServiceMockRecorder {
	return m.recorder
}

// FindIn mocks base method.
func (m *MockIUsageUnitService) FindIn(ctx context.Context, filter usageUnit.FilterReq) ([]usageUnit.UsageUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIn", ctx, filter)
	ret0, _ := ret[0].([]usageUnit.UsageUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIn indicates an expected call of FindIn.
func (mr *MockIUsageUnitServiceMockRecorder) FindIn(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIn", reflect.TypeOf((*MockIUsageUnitService)(nil).FindIn), ctx, filter)
}
