// Code generated by MockGen. DO NOT EDIT.
// Source: ./core.go
//
// Generated by this command:
//
//	mockgen -source=./core.go -destination=./core_mock.go -package=mockCore
//

// Package mockCore is a generated GoMock package.
package mockCore

import (
	reflect "reflect"

	core "github.com/hifat/goroger-core"
	gomock "go.uber.org/mock/gomock"
)

// Mockhelper is a mock of helper interface.
type Mockhelper struct {
	ctrl     *gomock.Controller
	recorder *MockhelperMockRecorder
}

// MockhelperMockRecorder is the mock recorder for Mockhelper.
type MockhelperMockRecorder struct {
	mock *Mockhelper
}

// NewMockhelper creates a new mock instance.
func NewMockhelper(ctrl *gomock.Controller) *Mockhelper {
	mock := &Mockhelper{ctrl: ctrl}
	mock.recorder = &MockhelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhelper) EXPECT() *MockhelperMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *Mockhelper) Copy(toValue, fromValue any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", toValue, fromValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockhelperMockRecorder) Copy(toValue, fromValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*Mockhelper)(nil).Copy), toValue, fromValue)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *Mocklogger) Debug(message string, fields ...core.LoggerField) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockloggerMockRecorder) Debug(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*Mocklogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *Mocklogger) Error(message any, fields ...core.LoggerField) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockloggerMockRecorder) Error(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mocklogger)(nil).Error), varargs...)
}

// Fatal mocks base method.
func (m *Mocklogger) Fatal(message string, fields ...core.LoggerField) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockloggerMockRecorder) Fatal(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*Mocklogger)(nil).Fatal), varargs...)
}

// Info mocks base method.
func (m *Mocklogger) Info(message string, fields ...core.LoggerField) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockloggerMockRecorder) Info(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*Mocklogger)(nil).Info), varargs...)
}

// Skip mocks base method.
func (m *Mocklogger) Skip(skip int) core.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skip", skip)
	ret0, _ := ret[0].(core.Logger)
	return ret0
}

// Skip indicates an expected call of Skip.
func (mr *MockloggerMockRecorder) Skip(skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*Mocklogger)(nil).Skip), skip)
}

// Warn mocks base method.
func (m *Mocklogger) Warn(message string, fields ...core.LoggerField) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockloggerMockRecorder) Warn(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*Mocklogger)(nil).Warn), varargs...)
}
