// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package authDi

import (
	"github.com/hifat/mallow-sale-api/internal/auth/handler"
	"github.com/hifat/mallow-sale-api/internal/auth/service"
	"github.com/hifat/mallow-sale-api/internal/user/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *authHandler.Handler {
	iLogger := logger.New()
	iRepository := userRepository.NewMongo(db)
	iService := authService.New(iLogger, cfg, iRepository)
	rest := authHandler.NewRest(iService)
	handler := authHandler.New(rest)
	return handler
}
