// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package supplierInventoryDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/supplier/inventory/handler"
	"github.com/hifat/mallow-sale-api/internal/supplier/inventory/service"
	"github.com/hifat/mallow-sale-api/internal/supplier/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *supplierInventoryHandler.Handler {
	iLogger := logger.New()
	iRepository := supplierRepository.NewMongo(db)
	inventoryModuleIRepository := inventoryRepository.NewMongo(db)
	iService := inventoryService.New(iLogger, iRepository, inventoryModuleIRepository)
	rest := supplierInventoryHandler.NewRest(iService)
	handler := supplierInventoryHandler.New(rest)
	return handler
}
