// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inventoryDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/handler"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/inventory/service"
	"github.com/hifat/mallow-sale-api/internal/pricePreset/repository"
	"github.com/hifat/mallow-sale-api/internal/recipe/repository"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *inventoryHandler.Handler {
	iLogger := logger.New()
	iRepository := inventoryRepository.NewMongo(db)
	usageUnitModuleIRepository := usageUnitRepository.NewMongo(db)
	pricePresetModuleIRepository := pricePresetRepository.NewMongo(db)
	recipeModuleIRepository := recipeRepository.NewMongo(db)
	iService := inventoryService.New(iLogger, iRepository, usageUnitModuleIRepository, pricePresetModuleIRepository, recipeModuleIRepository)
	rest := inventoryHandler.NewRest(iService)
	grpc := inventoryHandler.NewGrpc(iService)
	handler := inventoryHandler.New(rest, grpc)
	return handler
}
