// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain.go
//
// Generated by this command:
//
//	mockgen -source=./domain.go -destination=./repository/mock/repository.go -package=mockShoppingRepository
//

// Package mockShoppingRepository is a generated GoMock package.
package mockShoppingRepository

import (
	context "context"
	reflect "reflect"

	shoppingModule "github.com/hifat/mallow-sale-api/internal/shopping"
	handling "github.com/hifat/mallow-sale-api/pkg/handling"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRepository) Create(ctx context.Context, req *shoppingModule.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRepository)(nil).Create), ctx, req)
}

// DeleteByID mocks base method.
func (m *MockIRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIRepository)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockIRepository) Find(ctx context.Context) ([]shoppingModule.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]shoppingModule.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIRepositoryMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIRepository)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockIRepository) FindByID(ctx context.Context, id string) (*shoppingModule.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*shoppingModule.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIRepository)(nil).FindByID), ctx, id)
}

// ReOrderNo mocks base method.
func (m *MockIRepository) ReOrderNo(ctx context.Context, reqs []shoppingModule.ReqReOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReOrderNo", ctx, reqs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReOrderNo indicates an expected call of ReOrderNo.
func (mr *MockIRepositoryMockRecorder) ReOrderNo(ctx, reqs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReOrderNo", reflect.TypeOf((*MockIRepository)(nil).ReOrderNo), ctx, reqs)
}

// UpdateByID mocks base method.
func (m *MockIRepository) UpdateByID(ctx context.Context, id string, req *shoppingModule.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIRepositoryMockRecorder) UpdateByID(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIRepository)(nil).UpdateByID), ctx, id, req)
}

// UpdateStatus mocks base method.
func (m *MockIRepository) UpdateStatus(ctx context.Context, id string, req *shoppingModule.ReqUpdateStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIRepositoryMockRecorder) UpdateStatus(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIRepository)(nil).UpdateStatus), ctx, id, req)
}

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIService) Create(ctx context.Context, req *shoppingModule.Request) (*handling.ResponseItem[*shoppingModule.Request], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*handling.ResponseItem[*shoppingModule.Request])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIService)(nil).Create), ctx, req)
}

// DeleteByID mocks base method.
func (m *MockIService) DeleteByID(ctx context.Context, id string) (*handling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(*handling.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIServiceMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIService)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockIService) Find(ctx context.Context) (*handling.ResponseItems[shoppingModule.Response], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].(*handling.ResponseItems[shoppingModule.Response])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIServiceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIService)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockIService) FindByID(ctx context.Context, id string) (*handling.ResponseItem[*shoppingModule.Response], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*handling.ResponseItem[*shoppingModule.Response])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIServiceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIService)(nil).FindByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockIService) UpdateByID(ctx context.Context, id string, req *shoppingModule.Request) (*handling.ResponseItem[*shoppingModule.Request], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, req)
	ret0, _ := ret[0].(*handling.ResponseItem[*shoppingModule.Request])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIServiceMockRecorder) UpdateByID(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIService)(nil).UpdateByID), ctx, id, req)
}

// UpdateStatus mocks base method.
func (m *MockIService) UpdateStatus(ctx context.Context, id string, req *shoppingModule.ReqUpdateStatus) (*handling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, req)
	ret0, _ := ret[0].(*handling.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIServiceMockRecorder) UpdateStatus(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIService)(nil).UpdateStatus), ctx, id, req)
}

// MockIInventoryRepository is a mock of IInventoryRepository interface.
type MockIInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInventoryRepositoryMockRecorder
}

// MockIInventoryRepositoryMockRecorder is the mock recorder for MockIInventoryRepository.
type MockIInventoryRepositoryMockRecorder struct {
	mock *MockIInventoryRepository
}

// NewMockIInventoryRepository creates a new mock instance.
func NewMockIInventoryRepository(ctrl *gomock.Controller) *MockIInventoryRepository {
	mock := &MockIInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockIInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInventoryRepository) EXPECT() *MockIInventoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIInventoryRepository) Create(ctx context.Context, req *shoppingModule.RequestShoppingInventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIInventoryRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInventoryRepository)(nil).Create), ctx, req)
}

// DeleteByID mocks base method.
func (m *MockIInventoryRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIInventoryRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIInventoryRepository)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockIInventoryRepository) Find(ctx context.Context) ([]shoppingModule.ResShoppingInventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]shoppingModule.ResShoppingInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIInventoryRepositoryMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIInventoryRepository)(nil).Find), ctx)
}

// MockIInventoryService is a mock of IInventoryService interface.
type MockIInventoryService struct {
	ctrl     *gomock.Controller
	recorder *MockIInventoryServiceMockRecorder
}

// MockIInventoryServiceMockRecorder is the mock recorder for MockIInventoryService.
type MockIInventoryServiceMockRecorder struct {
	mock *MockIInventoryService
}

// NewMockIInventoryService creates a new mock instance.
func NewMockIInventoryService(ctrl *gomock.Controller) *MockIInventoryService {
	mock := &MockIInventoryService{ctrl: ctrl}
	mock.recorder = &MockIInventoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInventoryService) EXPECT() *MockIInventoryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIInventoryService) Create(ctx context.Context, req *shoppingModule.RequestShoppingInventory) (*handling.ResponseItem[*shoppingModule.RequestShoppingInventory], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*handling.ResponseItem[*shoppingModule.RequestShoppingInventory])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIInventoryServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInventoryService)(nil).Create), ctx, req)
}

// DeleteByID mocks base method.
func (m *MockIInventoryService) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIInventoryServiceMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIInventoryService)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockIInventoryService) Find(ctx context.Context) (*handling.ResponseItems[shoppingModule.ResShoppingInventory], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].(*handling.ResponseItems[shoppingModule.ResShoppingInventory])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIInventoryServiceMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIInventoryService)(nil).Find), ctx)
}

// MockIReceiptGrpcRepository is a mock of IReceiptGrpcRepository interface.
type MockIReceiptGrpcRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIReceiptGrpcRepositoryMockRecorder
}

// MockIReceiptGrpcRepositoryMockRecorder is the mock recorder for MockIReceiptGrpcRepository.
type MockIReceiptGrpcRepositoryMockRecorder struct {
	mock *MockIReceiptGrpcRepository
}

// NewMockIReceiptGrpcRepository creates a new mock instance.
func NewMockIReceiptGrpcRepository(ctrl *gomock.Controller) *MockIReceiptGrpcRepository {
	mock := &MockIReceiptGrpcRepository{ctrl: ctrl}
	mock.recorder = &MockIReceiptGrpcRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReceiptGrpcRepository) EXPECT() *MockIReceiptGrpcRepositoryMockRecorder {
	return m.recorder
}

// ReadReceipt mocks base method.
func (m *MockIReceiptGrpcRepository) ReadReceipt(ctx context.Context, fileName string, file []byte) ([]shoppingModule.ResReceiptReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadReceipt", ctx, fileName, file)
	ret0, _ := ret[0].([]shoppingModule.ResReceiptReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadReceipt indicates an expected call of ReadReceipt.
func (mr *MockIReceiptGrpcRepositoryMockRecorder) ReadReceipt(ctx, fileName, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadReceipt", reflect.TypeOf((*MockIReceiptGrpcRepository)(nil).ReadReceipt), ctx, fileName, file)
}

// MockIReceiptService is a mock of IReceiptService interface.
type MockIReceiptService struct {
	ctrl     *gomock.Controller
	recorder *MockIReceiptServiceMockRecorder
}

// MockIReceiptServiceMockRecorder is the mock recorder for MockIReceiptService.
type MockIReceiptServiceMockRecorder struct {
	mock *MockIReceiptService
}

// NewMockIReceiptService creates a new mock instance.
func NewMockIReceiptService(ctrl *gomock.Controller) *MockIReceiptService {
	mock := &MockIReceiptService{ctrl: ctrl}
	mock.recorder = &MockIReceiptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReceiptService) EXPECT() *MockIReceiptServiceMockRecorder {
	return m.recorder
}

// Reader mocks base method.
func (m *MockIReceiptService) Reader(ctx context.Context, req *shoppingModule.ReqReceiptReader) (*handling.ResponseItems[shoppingModule.ResReceiptReader], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", ctx, req)
	ret0, _ := ret[0].(*handling.ResponseItems[shoppingModule.ResReceiptReader])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockIReceiptServiceMockRecorder) Reader(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockIReceiptService)(nil).Reader), ctx, req)
}
