// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inventoryDI

import (
	"github.com/google/wire"
	"github.com/hifat/cost-calculator-api/config"
	"github.com/hifat/cost-calculator-api/internal/inventory/inventoryHandler"
	"github.com/hifat/cost-calculator-api/internal/inventory/inventoryRepository"
	"github.com/hifat/cost-calculator-api/internal/inventory/inventoryService"
	"github.com/hifat/goroger-core/helper"
	"github.com/hifat/goroger-core/logger"
	"go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database, log *zap.Logger) inventoryHandler.Handler {
	coreHelper := helper.New()
	iInventoryRepository := inventoryRepository.NewMongo(db, coreHelper)
	coreLogger := logger.New(log)
	iInventoryService := inventoryService.New(iInventoryRepository, coreHelper, coreLogger)
	inventoryRest := inventoryHandler.NewRest(iInventoryService)
	handler := inventoryHandler.New(inventoryRest)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(inventoryRepository.NewMongo)

var ServiceSet = wire.NewSet(helper.New, logger.New, inventoryService.New)

var HandlerSet = wire.NewSet(inventoryHandler.New, inventoryHandler.NewRest)
