// Code generated by MockGen. DO NOT EDIT.
// Source: ./grpc.go
//
// Generated by this command:
//
//	mockgen -source=./grpc.go -destination=./mock/grpc.go -package=mockUsageUnitRepository
//

// Package mockUsageUnitRepository is a generated GoMock package.
package mockUsageUnitRepository

import (
	context "context"
	reflect "reflect"

	usageUnit "github.com/hifat/mallow-sale-api/internal/usageUnit"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsageUnitGRPCRepository is a mock of IUsageUnitGRPCRepository interface.
type MockIUsageUnitGRPCRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUsageUnitGRPCRepositoryMockRecorder
}

// MockIUsageUnitGRPCRepositoryMockRecorder is the mock recorder for MockIUsageUnitGRPCRepository.
type MockIUsageUnitGRPCRepositoryMockRecorder struct {
	mock *MockIUsageUnitGRPCRepository
}

// NewMockIUsageUnitGRPCRepository creates a new mock instance.
func NewMockIUsageUnitGRPCRepository(ctrl *gomock.Controller) *MockIUsageUnitGRPCRepository {
	mock := &MockIUsageUnitGRPCRepository{ctrl: ctrl}
	mock.recorder = &MockIUsageUnitGRPCRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsageUnitGRPCRepository) EXPECT() *MockIUsageUnitGRPCRepositoryMockRecorder {
	return m.recorder
}

// FindIn mocks base method.
func (m *MockIUsageUnitGRPCRepository) FindIn(ctx context.Context, filter usageUnit.FilterReq) ([]usageUnit.UsageUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIn", ctx, filter)
	ret0, _ := ret[0].([]usageUnit.UsageUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIn indicates an expected call of FindIn.
func (mr *MockIUsageUnitGRPCRepositoryMockRecorder) FindIn(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIn", reflect.TypeOf((*MockIUsageUnitGRPCRepository)(nil).FindIn), ctx, filter)
}
