// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mockUsageUnitRepository
//

// Package mockUsageUnitRepository is a generated GoMock package.
package mockUsageUnitRepository

import (
	context "context"
	reflect "reflect"

	usageUnit "github.com/hifat/mallow-sale-api/internal/usageUnit"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsageUnitRepository is a mock of IUsageUnitRepository interface.
type MockIUsageUnitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUsageUnitRepositoryMockRecorder
}

// MockIUsageUnitRepositoryMockRecorder is the mock recorder for MockIUsageUnitRepository.
type MockIUsageUnitRepositoryMockRecorder struct {
	mock *MockIUsageUnitRepository
}

// NewMockIUsageUnitRepository creates a new mock instance.
func NewMockIUsageUnitRepository(ctrl *gomock.Controller) *MockIUsageUnitRepository {
	mock := &MockIUsageUnitRepository{ctrl: ctrl}
	mock.recorder = &MockIUsageUnitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsageUnitRepository) EXPECT() *MockIUsageUnitRepositoryMockRecorder {
	return m.recorder
}

// FindInCodes mocks base method.
func (m *MockIUsageUnitRepository) FindInCodes(ctx context.Context, codes []string) ([]usageUnit.UsageUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInCodes", ctx, codes)
	ret0, _ := ret[0].([]usageUnit.UsageUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInCodes indicates an expected call of FindInCodes.
func (mr *MockIUsageUnitRepositoryMockRecorder) FindInCodes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInCodes", reflect.TypeOf((*MockIUsageUnitRepository)(nil).FindInCodes), ctx, codes)
}
