// Code generated by MockGen. DO NOT EDIT.
// Source: ./mongo.go
//
// Generated by this command:
//
//	mockgen -source=./mongo.go -destination=./mock/mongo.go -package=mockRecipeRepository
//

// Package mockRecipeRepository is a generated GoMock package.
package mockRecipeRepository
