// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=./mock/repository.go -package=mockRecipeRepository
//

// Package mockRecipeRepository is a generated GoMock package.
package mockRecipeRepository

import (
	context "context"
	reflect "reflect"

	recipe "github.com/hifat/mallow-sale-api/internal/recipe"
	gomock "go.uber.org/mock/gomock"
)

// MockIRecipeRepository is a mock of IRecipeRepository interface.
type MockIRecipeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRecipeRepositoryMockRecorder
}

// MockIRecipeRepositoryMockRecorder is the mock recorder for MockIRecipeRepository.
type MockIRecipeRepositoryMockRecorder struct {
	mock *MockIRecipeRepository
}

// NewMockIRecipeRepository creates a new mock instance.
func NewMockIRecipeRepository(ctrl *gomock.Controller) *MockIRecipeRepository {
	mock := &MockIRecipeRepository{ctrl: ctrl}
	mock.recorder = &MockIRecipeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecipeRepository) EXPECT() *MockIRecipeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRecipeRepository) Create(ctx context.Context, req recipe.RecipeReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIRecipeRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRecipeRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockIRecipeRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRecipeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRecipeRepository)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockIRecipeRepository) Find(ctx context.Context) ([]recipe.RecipeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]recipe.RecipeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIRecipeRepositoryMockRecorder) Find(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIRecipeRepository)(nil).Find), ctx)
}

// FindByID mocks base method.
func (m *MockIRecipeRepository) FindByID(ctx context.Context, id string) (*recipe.RecipeRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*recipe.RecipeRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIRecipeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIRecipeRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockIRecipeRepository) Update(ctx context.Context, id string, req recipe.UpdateRecipeReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRecipeRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRecipeRepository)(nil).Update), ctx, id, req)
}
