// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package shoppingDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/shopping/handler"
	"github.com/hifat/mallow-sale-api/internal/shopping/repository"
	"github.com/hifat/mallow-sale-api/internal/shopping/service"
	"github.com/hifat/mallow-sale-api/internal/supplier/helper"
	"github.com/hifat/mallow-sale-api/internal/supplier/repository"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/helper"
	"github.com/hifat/mallow-sale-api/internal/usageUnit/repository"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

//
//go:generate wire ./wire.go
func Init(cfg *config.Config, db *mongo.Database, grpcConn *grpc.ClientConn) *shoppingHandler.Handler {
	iLogger := logger.New()
	iRepository := shoppingRepository.NewMongo(db)
	usageUnitModuleIRepository := usageUnitRepository.NewMongo(db)
	iHelper := usageUnitHelper.New(iLogger, usageUnitModuleIRepository)
	supplierModuleIRepository := supplierRepository.NewMongo(db)
	supplierHelperIHelper := supplierHelper.New(supplierModuleIRepository)
	inventoryModuleIRepository := inventoryRepository.NewMongo(db)
	inventoryHelperIHelper := inventoryHelper.New(inventoryModuleIRepository)
	iService := shoppingService.New(iLogger, iRepository, usageUnitModuleIRepository, iHelper, supplierHelperIHelper, inventoryHelperIHelper)
	rest := shoppingHandler.NewRest(iService)
	iInventoryRepository := shoppingRepository.NewInventoryMongo(db)
	iInventoryService := shoppingService.NewInventory(iInventoryRepository, inventoryModuleIRepository, supplierModuleIRepository, iLogger)
	inventoryRest := shoppingHandler.NewInventoryRest(iInventoryService)
	iReceiptGrpcRepository := shoppingRepository.NewReceiptGRPC(grpcConn)
	iReceiptService := shoppingService.NewReceipt(iLogger, iReceiptGrpcRepository)
	receiptRest := shoppingHandler.NewReceiptRest(iReceiptService)
	iUsageUnitRepository := shoppingRepository.NewUsageUnitMongo(db)
	iUsageUnitService := shoppingService.NewUsageUnit(iLogger, iUsageUnitRepository)
	usageUnitRest := shoppingHandler.NewUsageUnitRest(iUsageUnitService)
	handler := shoppingHandler.New(rest, inventoryRest, receiptRest, usageUnitRest)
	return handler
}
