basePath: /api/v1
definitions:
  github_com_hifat_mallow-sale-api_internal_inventory.Prototype:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      purchase_price:
        type: number
      purchase_quantity:
        type: number
      purchase_unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.Prototype'
      remark:
        type: string
      updated_at:
        type: string
      yield_percentage:
        type: number
    required:
    - name
    - purchase_price
    - purchase_quantity
    - yield_percentage
    type: object
  github_com_hifat_mallow-sale-api_internal_inventory.Request:
    properties:
      name:
        type: string
      purchase_price:
        type: number
      purchase_quantity:
        type: number
      purchase_unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.UsageUnitReq'
      remark:
        type: string
      yield_percentage:
        type: number
    required:
    - name
    - purchase_price
    - purchase_quantity
    - yield_percentage
    type: object
  github_com_hifat_mallow-sale-api_internal_inventory.Response:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      purchase_price:
        type: number
      purchase_quantity:
        type: number
      purchase_unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.Prototype'
      remark:
        type: string
      updated_at:
        type: string
      yield_percentage:
        type: number
    required:
    - name
    - purchase_price
    - purchase_quantity
    - yield_percentage
    type: object
  github_com_hifat_mallow-sale-api_internal_recipe.IngredientPrototype:
    properties:
      inventory:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Prototype'
      inventory_id:
        type: string
      quantity:
        type: number
      unit:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_internal_recipe.IngredientRequest:
    properties:
      inventory_id:
        type: string
      quantity:
        type: number
      unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.UsageUnitReq'
    required:
    - inventory_id
    - quantity
    - unit
    type: object
  github_com_hifat_mallow-sale-api_internal_recipe.Request:
    properties:
      ingredients:
        items:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.IngredientRequest'
        type: array
      name:
        type: string
    required:
    - ingredients
    - name
    type: object
  github_com_hifat_mallow-sale-api_internal_recipe.Response:
    properties:
      created_at:
        type: string
      id:
        type: string
      ingredients:
        items:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.IngredientPrototype'
        type: array
      name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_internal_usageUnit.Prototype:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_internal_usageUnit.UsageUnitReq:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.MetaResponse:
    properties:
      total:
        type: integer
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_inventory_Request:
    properties:
      item:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Request'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_inventory_Response:
    properties:
      item:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_recipe_Request:
    properties:
      item:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.Request'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_recipe_Response:
    properties:
      item:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.Response'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_inventory_Response:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
        type: array
      meta:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.MetaResponse'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_recipe_Response:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.Response'
        type: array
      meta:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.MetaResponse'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A REST API for managing inventory and sales
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mallow Sale API
  version: "1.0"
paths:
  /inventories:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_inventory_Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Find Inventories
      tags:
      - inventory
    post:
      consumes:
      - application/json
      parameters:
      - description: Created inventory data
        in: body
        name: inventory
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_inventory_Request'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Create Inventory
      tags:
      - inventory
  /inventories/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Inventory ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Delete Inventory by ID
      tags:
      - inventory
    get:
      consumes:
      - application/json
      parameters:
      - description: inventoryID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_inventory_Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Find Inventory by ID
      tags:
      - inventory
    put:
      consumes:
      - application/json
      parameters:
      - description: inventory ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated inventory data
        in: body
        name: inventory
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_inventory_Request'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Update Inventory by ID
      tags:
      - inventory
  /recipes:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_recipe_Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Find Recipes
      tags:
      - recipe
    post:
      consumes:
      - application/json
      parameters:
      - description: Created recipe data
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_recipe_Request'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Create Recipe
      tags:
      - recipe
  /recipes/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Delete Recipe by ID
      tags:
      - recipe
    get:
      consumes:
      - application/json
      parameters:
      - description: recipeID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_recipe_Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Find Recipe by ID
      tags:
      - recipe
    put:
      consumes:
      - application/json
      parameters:
      - description: recipe ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated recipe data
        in: body
        name: recipe
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_recipe.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItem-github_com_hifat_mallow-sale-api_internal_recipe_Request'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Update Recipe by ID
      tags:
      - recipe
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
