basePath: /api/v1
definitions:
  github_com_hifat_mallow-sale-api_internal_inventory.Request:
    properties:
      name:
        type: string
      purchase_price:
        type: number
      purchase_quantity:
        type: number
      purchase_unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.UsageUnitReq'
      remark:
        type: string
      yield_percentage:
        type: number
    required:
    - name
    - purchase_price
    - purchase_quantity
    - yield_percentage
    type: object
  github_com_hifat_mallow-sale-api_internal_inventory.Response:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      purchase_price:
        type: number
      purchase_quantity:
        type: number
      purchase_unit:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_usageUnit.Prototype'
      remark:
        type: string
      updated_at:
        type: string
      yield_percentage:
        type: number
    required:
    - name
    - purchase_price
    - purchase_quantity
    - yield_percentage
    type: object
  github_com_hifat_mallow-sale-api_internal_usageUnit.Prototype:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_internal_usageUnit.UsageUnitReq:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.MetaResponse:
    properties:
      total:
        type: integer
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_inventory_Response:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
        type: array
      meta:
        $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.MetaResponse'
    type: object
  github_com_hifat_mallow-sale-api_pkg_handling.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A REST API for managing inventory and sales
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mallow Sale API
  version: "1.0"
paths:
  /inventories:
    get:
      consumes:
      - application/json
      description: Retrieve all inventory items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ResponseItems-github_com_hifat_mallow-sale-api_internal_inventory_Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Get all inventory items
      tags:
      - inventory
    post:
      consumes:
      - application/json
      description: Create a new inventory item with the provided details
      parameters:
      - description: Inventory item to create
        in: body
        name: inventory
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Create a new inventory item
      tags:
      - inventory
  /inventories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific inventory item by its ID
      parameters:
      - description: Inventory item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Delete inventory item by ID
      tags:
      - inventory
    get:
      consumes:
      - application/json
      description: Retrieve a specific inventory item by its ID
      parameters:
      - description: Inventory item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Get inventory item by ID
      tags:
      - inventory
    put:
      consumes:
      - application/json
      description: Update a specific inventory item by its ID
      parameters:
      - description: Inventory item ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated inventory item data
        in: body
        name: inventory
        required: true
        schema:
          $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_internal_inventory.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_hifat_mallow-sale-api_pkg_handling.ErrorResponse'
      summary: Update inventory item by ID
      tags:
      - inventory
  /inventories/ping:
    get:
      consumes:
      - application/json
      description: A simple ping endpoint to check if the server is running
      produces:
      - application/json
      responses:
        "200":
          description: Server is running
          schema:
            additionalProperties: true
            type: object
      summary: Ping endpoint
      tags:
      - health
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
