// Code generated by MockGen. DO NOT EDIT.
// Source: ./rules.go
//
// Generated by this command:
//
//	mockgen -source=./rules.go -destination=./rules_mock.go -package=mockRules
//

// Package mockRules is a generated GoMock package.
package mockRules

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockvalidator is a mock of validator interface.
type Mockvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockvalidatorMockRecorder
}

// MockvalidatorMockRecorder is the mock recorder for Mockvalidator.
type MockvalidatorMockRecorder struct {
	mock *Mockvalidator
}

// NewMockvalidator creates a new mock instance.
func NewMockvalidator(ctrl *gomock.Controller) *Mockvalidator {
	mock := &Mockvalidator{ctrl: ctrl}
	mock.recorder = &MockvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockvalidator) EXPECT() *MockvalidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *Mockvalidator) Validate(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockvalidatorMockRecorder) Validate(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*Mockvalidator)(nil).Validate), v)
}
