// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pricePresetDi

import (
	"github.com/hifat/mallow-sale-api/internal/inventory/helper"
	"github.com/hifat/mallow-sale-api/internal/inventory/repository"
	"github.com/hifat/mallow-sale-api/internal/pricePreset/handler"
	"github.com/hifat/mallow-sale-api/internal/pricePreset/repository"
	"github.com/hifat/mallow-sale-api/internal/pricePreset/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *pricePresetHandler.Handler {
	iRepository := pricePresetRepository.NewMongo(db)
	inventoryModuleIRepository := inventoryRepository.NewMongo(db)
	iHelper := inventoryHelper.New(inventoryModuleIRepository)
	iLogger := logger.New()
	iService := pricePresetService.New(iRepository, iHelper, iLogger)
	rest := pricePresetHandler.NewRest(iService)
	handler := pricePresetHandler.New(rest)
	return handler
}
