// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: internal/usageUnit/usageUnitProto/usageUnit.proto

package usageUnitProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsageUnitGrpcServiceClient is the client API for UsageUnitGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsageUnitGrpcServiceClient interface {
	FindIn(ctx context.Context, in *InFilter, opts ...grpc.CallOption) (*UsageUnitRes, error)
}

type usageUnitGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageUnitGrpcServiceClient(cc grpc.ClientConnInterface) UsageUnitGrpcServiceClient {
	return &usageUnitGrpcServiceClient{cc}
}

func (c *usageUnitGrpcServiceClient) FindIn(ctx context.Context, in *InFilter, opts ...grpc.CallOption) (*UsageUnitRes, error) {
	out := new(UsageUnitRes)
	err := c.cc.Invoke(ctx, "/usageUnitProto.UsageUnitGrpcService/FindIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageUnitGrpcServiceServer is the server API for UsageUnitGrpcService service.
// All implementations must embed UnimplementedUsageUnitGrpcServiceServer
// for forward compatibility
type UsageUnitGrpcServiceServer interface {
	FindIn(context.Context, *InFilter) (*UsageUnitRes, error)
	mustEmbedUnimplementedUsageUnitGrpcServiceServer()
}

// UnimplementedUsageUnitGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUsageUnitGrpcServiceServer struct {
}

func (UnimplementedUsageUnitGrpcServiceServer) FindIn(context.Context, *InFilter) (*UsageUnitRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindIn not implemented")
}
func (UnimplementedUsageUnitGrpcServiceServer) mustEmbedUnimplementedUsageUnitGrpcServiceServer() {}

// UnsafeUsageUnitGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageUnitGrpcServiceServer will
// result in compilation errors.
type UnsafeUsageUnitGrpcServiceServer interface {
	mustEmbedUnimplementedUsageUnitGrpcServiceServer()
}

func RegisterUsageUnitGrpcServiceServer(s grpc.ServiceRegistrar, srv UsageUnitGrpcServiceServer) {
	s.RegisterService(&UsageUnitGrpcService_ServiceDesc, srv)
}

func _UsageUnitGrpcService_FindIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageUnitGrpcServiceServer).FindIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usageUnitProto.UsageUnitGrpcService/FindIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageUnitGrpcServiceServer).FindIn(ctx, req.(*InFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// UsageUnitGrpcService_ServiceDesc is the grpc.ServiceDesc for UsageUnitGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageUnitGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usageUnitProto.UsageUnitGrpcService",
	HandlerType: (*UsageUnitGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindIn",
			Handler:    _UsageUnitGrpcService_FindIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/usageUnit/usageUnitProto/usageUnit.proto",
}
