// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/usageUnit/usageUnitProto/usageUnit.proto

package usageUnitProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InFilter) Reset() {
	*x = InFilter{}
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFilter) ProtoMessage() {}

func (x *InFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFilter.ProtoReflect.Descriptor instead.
func (*InFilter) Descriptor() ([]byte, []int) {
	return file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescGZIP(), []int{0}
}

func (x *InFilter) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type UsageUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageUnit) Reset() {
	*x = UsageUnit{}
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageUnit) ProtoMessage() {}

func (x *UsageUnit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageUnit.ProtoReflect.Descriptor instead.
func (*UsageUnit) Descriptor() ([]byte, []int) {
	return file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescGZIP(), []int{1}
}

func (x *UsageUnit) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UsageUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UsageUnitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UsageUnit           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageUnitRes) Reset() {
	*x = UsageUnitRes{}
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageUnitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageUnitRes) ProtoMessage() {}

func (x *UsageUnitRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageUnitRes.ProtoReflect.Descriptor instead.
func (*UsageUnitRes) Descriptor() ([]byte, []int) {
	return file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescGZIP(), []int{2}
}

func (x *UsageUnitRes) GetItems() []*UsageUnit {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_usageUnit_usageUnitProto_usageUnit_proto protoreflect.FileDescriptor

const file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDesc = "" +
	"\n" +
	"1internal/usageUnit/usageUnitProto/usageUnit.proto\x12\x0eusageUnitProto\" \n" +
	"\bInFilter\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"3\n" +
	"\tUsageUnit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\fUsageUnitRes\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.usageUnitProto.UsageUnitR\x05items2X\n" +
	"\x14UsageUnitGrpcService\x12@\n" +
	"\x06FindIn\x12\x18.usageUnitProto.InFilter\x1a\x1c.usageUnitProto.UsageUnitResB\x12Z\x10./usageUnitProtob\x06proto3"

var (
	file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescOnce sync.Once
	file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescData []byte
)

func file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescGZIP() []byte {
	file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescOnce.Do(func() {
		file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDesc), len(file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDesc)))
	})
	return file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDescData
}

var file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_usageUnit_usageUnitProto_usageUnit_proto_goTypes = []any{
	(*InFilter)(nil),     // 0: usageUnitProto.InFilter
	(*UsageUnit)(nil),    // 1: usageUnitProto.UsageUnit
	(*UsageUnitRes)(nil), // 2: usageUnitProto.UsageUnitRes
}
var file_internal_usageUnit_usageUnitProto_usageUnit_proto_depIdxs = []int32{
	1, // 0: usageUnitProto.UsageUnitRes.items:type_name -> usageUnitProto.UsageUnit
	0, // 1: usageUnitProto.UsageUnitGrpcService.FindIn:input_type -> usageUnitProto.InFilter
	2, // 2: usageUnitProto.UsageUnitGrpcService.FindIn:output_type -> usageUnitProto.UsageUnitRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_usageUnit_usageUnitProto_usageUnit_proto_init() }
func file_internal_usageUnit_usageUnitProto_usageUnit_proto_init() {
	if File_internal_usageUnit_usageUnitProto_usageUnit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDesc), len(file_internal_usageUnit_usageUnitProto_usageUnit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_usageUnit_usageUnitProto_usageUnit_proto_goTypes,
		DependencyIndexes: file_internal_usageUnit_usageUnitProto_usageUnit_proto_depIdxs,
		MessageInfos:      file_internal_usageUnit_usageUnitProto_usageUnit_proto_msgTypes,
	}.Build()
	File_internal_usageUnit_usageUnitProto_usageUnit_proto = out.File
	file_internal_usageUnit_usageUnitProto_usageUnit_proto_goTypes = nil
	file_internal_usageUnit_usageUnitProto_usageUnit_proto_depIdxs = nil
}
