// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package supplierDi

import (
	"github.com/hifat/mallow-sale-api/internal/supplier/handler"
	"github.com/hifat/mallow-sale-api/internal/supplier/repository"
	"github.com/hifat/mallow-sale-api/internal/supplier/service"
	"github.com/hifat/mallow-sale-api/pkg/config"
	"github.com/hifat/mallow-sale-api/pkg/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func Init(cfg *config.Config, db *mongo.Database) *supplierHandler.Handler {
	iLogger := logger.New()
	iRepository := supplierRepository.NewMongo(db)
	iService := supplierService.New(iLogger, iRepository)
	rest := supplierHandler.NewRest(iService)
	handler := supplierHandler.New(rest)
	return handler
}
